# services.yaml

start_engine:
  description: "Start the vehicle engine"
  fields:
    vin:
      description: "Vehicle Identification Number"
      example: "1HGCM82633A123456"

stop_engine:
  description: "Stop the vehicle engine"
  fields:
    vin:
      description: "Vehicle Identification Number"
      example: "1HGCM82633A123456"

start_charging:
  description: "Start vehicle charging"
  fields:
    vin:
      description: "Vehicle Identification Number"
      example: "1HGCM82633A123456"

stop_charging:
  description: "Stop vehicle charging"
  fields:
    vin:
      description: "Vehicle Identification Number"
      example: "1HGCM82633A123456"
